version: 0.2

phases:
  install:
    commands:
  pre_build:
    commands:
  build:
    commands:
      - echo "Deployment into Production Environment"
      - npm install -g serverless
      - npm install --production
      - serverless deploy --stage prod --verbose
  post_build:
    commands: